name: Bloggingchrome
title: Bloggingchrome
author: Paolo Riccardi
description: Personal Resume and CS Blog 
lang: en
#url: http://paoloriccardi.github.io
url: https://www.bloggingchrome.it
baseurl: ""

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
